# Copyright 2026 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

"""remove user role

Revision ID: 109a6afdf170
Revises: fb04d94673c6
Create Date: 2026-01-20 13:14:41.089008

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "109a6afdf170"
down_revision: str | None = "fb04d94673c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role_updated_at")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Cannot migrate user roles from keyclok back to database")
    # ### end Alembic commands ###
