# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""empty message

Revision ID: 15e0c8efe77f
Revises: 214ed3790c6d
Create Date: 2025-11-25 11:41:35.660389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15e0c8efe77f"
down_revision: str | None = "214ed3790c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("a2a_request_tasks", sa.Column("trace_id", sa.String(length=256), nullable=True))
    op.add_column("user_feedback", sa.Column("trace_id", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_feedback", "trace_id")
    op.drop_column("a2a_request_tasks", "trace_id")
    # ### end Alembic commands ###
