# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add provider origins, build actions

Revision ID: 2626892a4e65
Revises: 73e2d8596ada
Create Date: 2025-10-08 12:35:26.872871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2626892a4e65"
down_revision: str | None = "73e2d8596ada"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE buildstate ADD VALUE 'build_completed'")
    op.add_column(
        "provider_builds",
        sa.Column("on_complete", sa.JSON(), nullable=False, server_default='{"type": "no_action"}'),
    )
    op.add_column("provider_builds", sa.Column("error_message", sa.Text(), nullable=True))

    op.execute("UPDATE providers SET auto_stop_timeout_sec = 0 WHERE auto_stop_timeout_sec IS NULL")
    op.alter_column("providers", "auto_stop_timeout_sec", existing_type=sa.INTEGER(), nullable=False)

    op.add_column("providers", sa.Column("origin", sa.String(length=2048), nullable=True))
    op.execute("UPDATE providers SET origin = SPLIT_PART(source, ':', 1)")
    op.alter_column("providers", "origin", nullable=False)

    op.add_column("providers", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE providers SET updated_at = created_at")
    op.alter_column("providers", "updated_at", nullable=False)

    op.create_unique_constraint(None, "providers", ["source"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("providers_source_key", "providers", type_="unique")
    op.drop_column("providers", "updated_at")
    op.drop_column("providers", "origin")
    op.drop_column("provider_builds", "error_message")
    op.drop_column("provider_builds", "on_complete")
    # ### end Alembic commands ###
