# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add optional provider_id relationship to context

Revision ID: 28725d931ca5
Revises: c69e8ad9a82a
Create Date: 2025-10-22 13:40:10.921827

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28725d931ca5"
down_revision: str | None = "c69e8ad9a82a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contexts", sa.Column("provider_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "contexts", "providers", ["provider_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contexts_provider_id_fkey", "contexts", type_="foreignkey")
    op.drop_column("contexts", "provider_id")
    # ### end Alembic commands ###
