# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""empty message

Revision ID: 4036d0817d69
Revises: 28725d931ca5
Create Date: 2025-10-27 13:33:32.430453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4036d0817d69"
down_revision: str | None = "28725d931ca5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("created", "auth_required", "connected", "disconnected", name="connectorstate"),
            nullable=True,
        ),
        sa.Column("auth", sa.JSON(), nullable=True),
        sa.Column("auth_state", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", "created_by", name="uk_url"),
    )
    op.create_index(op.f("ix_connectors_auth_state"), "connectors", ["auth_state"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connectors_auth_state"), table_name="connectors")
    op.drop_table("connectors")
    # ### end Alembic commands ###
