# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add content_type column to files

Revision ID: 5dec926744d0
Revises: 779011da771d
Create Date: 2025-08-19 10:13:37.795705

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dec926744d0"
down_revision: str | None = "779011da771d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("content_type", sa.String(length=256), nullable=True))
    # BREAKING CHANGE: placeholder content type for existing files - will be inconsistent with the actual content type
    op.execute("UPDATE files SET content_type = 'application/octet-stream'")
    op.alter_column("files", "content_type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "content_type")
    # ### end Alembic commands ###
