# Copyright 2026 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

"""add unmanaged state and registry to model providers

Revision ID: 764ca0fd6a5b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-05 11:57:11.032871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "764ca0fd6a5b"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


modelproviderstate_enum = sa.Enum("online", "offline", name="modelproviderstate")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    modelproviderstate_enum.create(op.get_bind())
    op.add_column("model_providers", sa.Column("registry", sa.String(length=2048), nullable=True))
    op.add_column(
        "model_providers",
        sa.Column(
            "state",
            modelproviderstate_enum,
            nullable=False,
            server_default="offline",
        ),
    )
    op.drop_index(op.f("ix_provider_discoveries_created_at"), table_name="provider_discoveries", if_exists=True)
    op.drop_index(op.f("ix_provider_discoveries_created_by"), table_name="provider_discoveries", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_providers", "state")
    op.drop_column("model_providers", "registry")
    modelproviderstate_enum.drop(op.get_bind())
    # ### end Alembic commands ###
