# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add context scoped resources

Revision ID: 779011da771d
Revises: b2d91792f9b5
Create Date: 2025-08-06 14:46:36.073362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "779011da771d"
down_revision: str | None = "b2d91792f9b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("files", sa.Column("context_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "files", "contexts", ["context_id"], ["id"], ondelete="CASCADE")
    op.add_column("vector_stores", sa.Column("context_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "vector_stores", "contexts", ["context_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vector_stores_context_id_fkey", "vector_stores", type_="foreignkey")
    op.drop_column("vector_stores", "context_id")
    op.drop_constraint("files_context_id_fkey", "files", type_="foreignkey")
    op.drop_column("files", "context_id")
    op.drop_table("contexts")
    # ### end Alembic commands ###
