# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add provider_id and build_configuration to provider_builds

Revision ID: c69e8ad9a82a
Revises: 8f8f9357862e
Create Date: 2025-10-16 14:35:20.641997

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c69e8ad9a82a"
down_revision: str | None = "8f8f9357862e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider_builds", sa.Column("build_configuration", sa.JSON(), nullable=True))
    op.add_column("provider_builds", sa.Column("provider_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "provider_builds", "providers", ["provider_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("provider_builds_provider_id_fkey", "provider_builds", type_="foreignkey")
    op.drop_column("provider_builds", "provider_id")
    op.drop_column("provider_builds", "build_configuration")
    # ### end Alembic commands ###
