# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0


from __future__ import annotations

"""add disconnect reason to connectors

Revision ID: fb04d94673c6
Revises: 4jowyo7q9m66
Create Date: 2026-01-22 10:10:10.911440

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb04d94673c6"
down_revision: str | None = "4jowyo7q9m66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connectors", sa.Column("disconnect_reason", sa.String(), nullable=True))
    op.add_column("connectors", sa.Column("disconnect_permanent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connectors", "disconnect_permanent")
    op.drop_column("connectors", "disconnect_reason")
    # ### end Alembic commands ###
