packages:
  - apps/agentstack-ui
  - apps/beeai-web
  - apps/lint-config
  - apps/agentstack-sdk-ts
  - docs

catalog:
  "@a2a-js/sdk": "^0.3.7"
  "@carbon/icons-react": ^11.71.0
  "@carbon/react": ^1.97.0
  "@svgr/webpack": ^8.1.0
  "@tanstack/react-query": ^5.90.12
  "@types/lodash": ^4.17.21
  "@types/node": ^22.19.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  clsx: ^2.1.1
  eslint: ^9.39.1
  lodash: ^4.17.21
  next: 15.5.7
  prettier: ^3.7.4
  react: ^19.2.1
  react-dom: ^19.2.1
  sass-embedded: ^1.93.3
  stylelint: ^16.26.1
  typescript: ^5.9.3
  usehooks-ts: ^3.1.1
