# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add user-scoped variables

Revision ID: 613a5534625e
Revises: 0ff485fef44f
Create Date: 2025-09-16 14:49:34.202200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "613a5534625e"
down_revision: str | None = "0ff485fef44f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column("variables", sa.Column("user_id", sa.UUID(), nullable=True))

    op.create_index("idx_entity_attributes_user", "variables", ["user_id"], unique=False)
    op.create_unique_constraint("uk_user", "variables", ["key", "parent_entity", "user_id"])

    op.create_foreign_key(
        "variables_user_id_fkey",
        "variables",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # update existing constraints
    op.drop_constraint("parent_entity_matches_reference", "variables")
    op.drop_constraint("exactly_one_reference", "variables")
    op.create_check_constraint(
        "parent_entity_matches_reference",
        "variables",
        (
            "(parent_entity = 'provider' AND provider_id IS NOT NULL) OR "
            "(parent_entity = 'model_provider' AND model_provider_id IS NOT NULL) OR"
            "(parent_entity = 'user' AND user_id IS NOT NULL)"
        ),
    )
    op.create_check_constraint(
        "exactly_one_reference",
        "variables",
        "(provider_id IS NOT NULL)::int + (model_provider_id IS NOT NULL)::int + (user_id IS NOT NULL)::int= 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("variables_user_id_fkey", "variables", type_="foreignkey")
    op.drop_constraint("uk_user", "variables", type_="unique")
    op.drop_index("idx_entity_attributes_user", table_name="variables")
    op.drop_column("variables", "user_id")
    # ### end Alembic commands ###
