# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add user ownership to providers

Revision ID: 73e2d8596ada
Revises: 613a5534625e
Create Date: 2025-10-01 13:12:33.873906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73e2d8596ada"
down_revision: str | None = "613a5534625e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("providers", sa.Column("created_by", sa.UUID(), nullable=True))
    # Assign existing providers to the admin user
    op.execute("UPDATE providers SET created_by = (SELECT id FROM users WHERE email = 'admin@beeai.dev')")
    op.alter_column("providers", "created_by", nullable=False)
    op.create_foreign_key(None, "providers", "users", ["created_by"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("providers_created_by_fkey", "providers", type_="foreignkey")
    op.drop_column("providers", "created_by")
    # ### end Alembic commands ###
