# Copyright 2026 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from datetime import timedelta
from typing import Protocol


class ICache[T](Protocol):
    async def add(self, key: str, value: T) -> bool: ...
    async def clear(self) -> bool: ...
    async def delete(self, key: str) -> int: ...
    async def exists(self, key: str) -> bool: ...
    async def get(self, key: str, default: T | None = None) -> T | None: ...
    async def multi_get(self, keys: list[str], default: T | None = None) -> list[T | None]: ...
    async def multi_set(self, pairs: list[tuple[str, T]]) -> bool: ...
    async def set(self, key: str, value: T) -> bool: ...
    async def close(self) -> None: ...


class ISerializer[T](Protocol):
    def dumps(self, value: T) -> str: ...
    def loads(self, value: str) -> T: ...


class ICacheFactory(Protocol):
    def create[T](
        self,
        *,
        namespace: str,
        serializer: ISerializer[T],
        ttl: timedelta | None = None,
        timeout_sec: float = 5.0,
    ) -> ICache[T]: ...
