{{-  if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeai-platform-ui
  labels:
    app: beeai-platform-ui
    {{- include "beeai-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: beeai-platform-ui
      {{- include "beeai-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: beeai-platform-ui
        {{- include "beeai-platform.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beeai-platform.serviceAccountName" . }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: beeai-platform-ui
          {{- with .Values.ui.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8334
              protocol: TCP
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: API_URL
              value: "http://beeai-platform-svc:{{.Values.service.port}}"
          {{- if and .Values.auth.enabled .Values.auth.oidc.enabled }}
            - name: OIDC__PROVIDERS_PATH
              value: {{ .Values.auth.oidc.providers_path }}
            - name: NEXTAUTH_URL
              value: {{ .Values.auth.oidc.nextauth_url }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: authSecret
                  name: beeai-next-auth
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_PROVIDERS
              valueFrom:
                secretKeyRef:
                  key: providers.json
                  name: oidc-providers
          {{- else}}
            - name: OIDC_ENABLED
              value: "false"
          {{- end }}
          volumeMounts:
            {{- with .Values.ui.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.ui.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
