{{-  if and .Values.auth.enabled .Values.auth.oidc.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: beeai-oidc-providers
  labels:
    app.kubernetes.io/component: beeai-ui
    app: beeai-ui
stringData:
  providers.json: |
    {{- toJson .Values.auth.oidc.providers | nindent 4 -}}
{{- end }}
