# setup

["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv sync --all-extras --dev"
sources = ["uv.lock", "pyproject.toml"]
outputs = { auto = true }

# check

["beeai-server:check"]
depends = ["beeai-server:check:*"]

["beeai-server:check:pytest-marks"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash

# Use pytest to collect tests that are not marked with unit, integration, or e2e
unmarked_tests=$(uv run pytest --collect-only --no-header --no-summary -q -m "not (unit or integration or e2e)" tests/ 2>/dev/null)

if echo "$unmarked_tests" | grep "tests collected" | grep -qv "no tests collected"; then
    echo "ERROR: Found tests without required pytest marks:\n"
    echo "$unmarked_tests" | grep 'tests collected'
    echo ""
    echo "All tests must be marked with @pytest.mark.unit, @pytest.mark.integration, or @pytest.mark.e2e"
    exit 1
else
    echo "✓ All tests have pytest marks"
fi
"""
sources = ["tests/**/*.py"]
outputs = { auto = true }

["beeai-server:check:ruff-check"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run ruff check --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-server:check:ruff-format"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run ruff format --quiet --check"
sources = ["src/**/*.py"]
outputs = { auto = true }

# TODO: Enable and fix issues in separate PR
# ["beeai-server:check:pyright"]
# depends = ["beeai-server:setup"]
# dir = "{{config_root}}/apps/beeai-server"
# run = "uv run pyright"
# sources = ["src/**/*.py"]
# outputs = { auto = true }

# fix

["beeai-server:fix"]
depends = ["beeai-server:fix:*"]

["beeai-server:fix:ruff-check"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run ruff check --quiet --fix"
sources = ["src/**/*.py"]
outputs = { auto = true }

["beeai-server:fix:ruff-format"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run ruff format --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

# run

["beeai-server:run"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run beeai-server"

# build

["beeai-server:build"]
depends = ["beeai-server:build:*"]
dir = "{{config_root}}/apps/beeai-server"
run = "docker build -t ghcr.io/i-am-bee/beeai-platform/beeai-server:local --load ."

["beeai-server:build:requirements"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "mkdir -p dist && uv export --no-hashes --no-emit-workspace --no-dev --format requirements-txt > dist/requirements.txt"
sources = ["uv.lock"]
outputs = ["dist/requirements.txt"]

["beeai-server:build:sdist"]
depends = ["beeai-server:setup"]
dir = "{{config_root}}/apps/beeai-server"
run = "rm ./dist/*.tar.gz 2>/dev/null || true; uv build --sdist --out-dir dist"
sources = ["pyproject.toml", "uv.lock", "src/**/*.py"]
outputs = ["dist/*.tar.gz"]

# migrations

["beeai-server:migrations:run"]
dir = "{{config_root}}/apps/beeai-server"
run = "uv run migrate"

["beeai-server:migrations:alembic:nocheck"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
set -a
source .env
set +a

cd src/beeai_server/infrastructure/persistence/migrations
uv run alembic {{arg(name="alembic_vars", var=true)}}
"""

["beeai-server:migrations:alembic"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
set -a
source .env
set +a

if ! telepresence list --replacements 2>/dev/null | grep -q platform; then
    echo "Dev env not running, use 'mise run beeai-server:dev:start' to start it..."
    exit 1
fi

cd src/beeai_server/infrastructure/persistence/migrations
uv run alembic {{arg(name="alembic_vars", var=true)}}
"""

["beeai-server:migrations:generate"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:migrations:alembic revision --autogenerate"

# dev

["beeai-server:dev:shell"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-platform:shell --vm-name=beeai-local-dev"

["beeai-server:dev:start"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
set -e
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
eval "$( {{ mise_bin }} run beeai-platform:shell --vm-name="$VM_NAME" )"
{{ mise_bin }} run beeai-server:dev:disconnect --vm-name="$VM_NAME"
{{ mise_bin }} run beeai-platform:stop-all --except "$VM_NAME"
{{ mise_bin }} beeai-platform:start --vm-name="$VM_NAME" {{arg(name="cli-args", var=true, default="--")}}
{{ mise_bin }} run beeai-server:dev:connect --vm-name="$VM_NAME"
"""

["beeai-server:dev:stop"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
{{ mise_bin }} run beeai-server:dev:disconnect --vm-name="$VM_NAME"
{{ mise_bin }} run beeai-platform:stop --vm-name=beeai-local-dev
"""

["beeai-server:dev:delete"]
dir = "{{config_root}}/apps/beeai-server"
run = """
VM_NAME={{option(name="vm-name", default="beeai-local-dev")}}
{{ mise_bin }} run beeai-cli:run -- platform delete --vm-name="$VM_NAME"
"""

["beeai-server:dev:connect"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
NAMESPACE=default
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
eval "$( {{ mise_bin }} run beeai-platform:shell --vm-name="$VM_NAME" )"

tele="telepresence --use .*${NAMESPACE}.*"
$tele helm install || true
$tele connect --namespace "$NAMESPACE"
$tele replace beeai-platform --port 18333:8333
"""

["beeai-server:dev:disconnect"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
NAMESPACE=default
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
eval "$( {{ mise_bin }} run beeai-platform:shell --vm-name="$VM_NAME" )"

tele="telepresence --use .*${NAMESPACE}.*"
$tele uninstall --all-agents || true
$tele quit
"""

["beeai-server:dev:reconnect"]
dir = "{{config_root}}/apps/beeai-server"
run = """
VM_NAME='{{option(name="vm-name", default="beeai-local-dev")}}'
{{ mise_bin }} run beeai-server:dev:disconnect --vm-name="$VM_NAME"
{{ mise_bin }} run beeai-server:dev:connect --vm-name="$VM_NAME"
"""

["beeai-server:dev:test:start"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:dev:start --vm-name=beeai-local-test --set externalRegistries=null"

["beeai-server:dev:test:delete"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:dev:delete --vm-name=beeai-local-test"

["beeai-server:dev:test:shell"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-platform:shell --vm-name=beeai-local-test"

["beeai-server:dev:test:connect"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:dev:connect --vm-name=beeai-local-test"

["beeai-server:dev:test:disconnect"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:dev:disconnect --vm-name=beeai-local-test"

["beeai-server:dev:test:reconnect"]
dir = "{{config_root}}/apps/beeai-server"
run = "{{ mise_bin }} run beeai-server:dev:reconnect --vm-name=beeai-local-test"

["beeai-server:test:e2e"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
VM_NAME=e2e-test-run

{{ mise_bin }} run beeai-platform:stop-all
{{ mise_bin }} run beeai-platform:delete --vm-name=${VM_NAME}
curl http://localhost:8333 >/dev/null 2>&1 && echo "Another instance at localhost:8333 is already running" && exit 2

{{ mise_bin }} run beeai-platform:start \
    --vm-name=${VM_NAME} \
    --set externalRegistries=null \
    --set docling.enabled=true \
    --set ui.enabled=false \
    --set auth.enabled="true" \
    --set auth.basic.enabled="true" \
    --set auth.basic.adminPassword="test-password" \
    --set auth.jwtSecretKey="test-secret-key"


eval "$( {{ mise_bin }} run beeai-platform:shell --vm-name="$VM_NAME" )"

export SERVER_URL="http://localhost:8333"
export DB_URL="postgresql+asyncpg://beeai-user:password@localhost:5432/beeai"
export LLM_API_BASE="${LLM_API_BASE:-http://host.docker.internal:11434/v1}"
export OIDC__DISABLE_OIDC=true

kubectl port-forward svc/postgresql 5432:5432 2>/dev/null 1>&2 &
uv run pytest -m e2e
result=$?

if [ $result -ne 0 ]; then
    echo "Tests failed. Checking pod status..."
    echo "------------- pods --------------"
    kubectl get pod
    echo "------------ events -------------"
    kubectl get event
fi

{{ mise_bin }} run beeai-cli:run -- platform delete --vm-name=${VM_NAME}
kill %1
exit $result
"""

["beeai-server:test:integration"]
dir = "{{config_root}}/apps/beeai-server"
run = """
#!/bin/bash
VM_NAME=itegration-test-run

{{ mise_bin }} run beeai-platform:delete --vm-name="$VM_NAME"

{{ mise_bin }} run beeai-platform:start \
    --vm-name="$VM_NAME" \
    --set externalRegistries=null \
    --set ui.enabled=false

eval "$( {{ mise_bin }} run beeai-platform:shell --vm-name="$VM_NAME" )"
export OIDC__DISABLE_OIDC=True

{{ mise_bin }} run beeai-server:dev:connect --vm-name="$VM_NAME"

uv run pytest -m integration
result=$?
exit $result
"""
